/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "2526v-li42d"
include("lecture-02-18-threads-intro")

include("lecture-02-24-synchro-intro")
include("lab1")
include("lecture-03-03-control-synchronization-intro")
include("lab2")
include("lecture-03-10-monitors-intro")
include("lecture-03-11-more-monitors")
include("lecture-03-17-timeout-and-cancellation")
include("lecture-03-25-kernel-style")
include("lecture-04-01-echo-server-scoped")
include("lab3")
include("lecture-04-14-memory-model")
include("lecture-04-15-coroutines-intro")
include("lab4")
include("lecture-04-22-more-coroutines")
include("lab4")
include("lab5")
include("lecture-04-29-async-io-intro")
include("lecture-05-06-coroutinesx-intro")
include("lecture-05-12-more-about-coroutines")
include("lecture-05-13-structured-concurrency")
include("lecture-05-20-flows-intro")